min_trimmed_length = 6
min_word_count = 3
max_word_count = 14
min_characters = 8
may_end_with_colon = false
quote_start_with_letter = true
needs_punctuation_end = true
needs_letter_start = true
needs_uppercase_start = false
allowed_symbols_regex = "[\u10D0-\u10F0„“,;:–  —\\-\\?\\.!]"
disallowed_symbols = []
broken_whitespace = ["  ", " ,", " .", " ?", " !", " ;", " :", "„ ", " “", "„“", "“-", "-,", ".“", " -", "- ", "?-"]

# Examples for each regex:
# - Most abbreviations at the end of a sentence
# - პროფ. / დაახლ. / მეცნ. / and other abbreviations
# - No words without vowels
# - No sentences end with a semicolon
# - Missing whitespace after comma, semicolon, etc.
# - Sentence delimiter can only be at the end of a sentence
# - No words with only one letter (" ა.", " ა:", "ა ", " ა ", " ა")
abbreviation_patterns = [
 "(\\s\\w{1}[^აეიოუს].$)|(\\s\\w{2}[^აეიოუთნრს].$)",
 "მო\\.|დას\\.|კულტ\\.|პროფ\\.|მეცნ\\.|მიახლ\\.|დაახლ\\.|დაახ\\.|ლათ\\.|გერ\\.|ინგლ\\.|რუს\\.|ბერძ\\.|მაგ[ \\.:]|მგუ[ \\.\\-]|ედპ[ \\.\\-]|სტუ[ \\.\\-]|თსუ|სსრ|ლკკ|აგგ|აშშ|ირბ|ნბა|ეცბ",
 "\\s[^აეიოუ]{2}+[\\s\\.\\-\\?!,;:“]",
 ";$",
 "[,:;]\\S",
 "[\\.|\\?|!].+$",
 "(^[\u10D0-\u10F0]{1}[\\s\\-,;:„“])|(\\s[\u10D0-\u10F0]{1}[\\s\\.\\?\\-!,;:„“])|(„[\u10D0-\u10F0]{1}[\\s\\.\\?\\-!,;:“])"
]
replacements = [
# - Replace abbreviations
  ["და სხვ.", "და სხვა."],
]
